id = "Marble"
name = "Marble"
version = "0.1.0"
schema_version = 1
authors = ["TeenCoder159 TeenCoder159@github.com"]
description = "Marble theme, a high contrast theme with blue, red green and orange, all while being pleasant to the eyes"
repository = "https://github.com/your-name/my-zed-extension"
